name: CI/CD

on:
    push:
        branches:
            - "+([0-9])?(.{+([0-9]),x}).x"
            - main
            - next
    pull_request:
        branches:
            - "+([0-9])?(.{+([0-9]),x}).x"
            - main
            - next

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v2
              with:
                  node-version: "17"
            - uses: hashicorp/setup-terraform@v1
              with:
                  terraform_version: "1.1.4"
            - uses: actions/cache@v2
              with:
                  path: .terraform/
                  key: ${{ hashFiles('.terraform.lock.hcl') }}
            - uses: actions/cache@v2
              with:
                  path: build/
                  key: ${{ github.sha }}

            - run: cp .github/.versionrc.js .
            - run: npx standard-version

            - run: terraform init
            - run: terraform fmt -check
            - run: terraform validate -no-color
            - run: mkdir -p build
            - run: cp -R .terraform.lock.hcl *.tf build
            - run: cp .env VERSION CHANNEL CHANGELOG build

    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - run: echo CodeCoverage

    release_git:
        needs: test
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache@v2
              with:
                  path: build/
                  key: ${{ github.sha }}

            - run: echo "VERSION=$(cat build/VERSION)" >> $GITHUB_ENV
            - run: echo "CHANNEL=$(cat build/CHANNEL)" >> $GITHUB_ENV
            - run: git tag ${{ env.VERSION }}
            - run: git push --tag
            - uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{ env.VERSION }}
                  prerelease: ${{ env.CHANNEL != 'latest' }}
                  body_path: build/CHANGELOG
                  files: build/**
